In [ ]:
import numpy as np

## Numpy

*   Library for mathematical and numerical functions.
*   np.array() function makes an array out of no. of elements.

## Arrays in Numpy

*   Same data type of all elements unlike list

In [ ]:
arr=np.array([1,2,3,4,5,6])

print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


.shape gives the dimension of the array

In [ ]:
arr.shape

(6,)

## Dimensions of Numpy

    1. 0 Dimension: Collection of a single element
        *   Ex. np.array(5)

In [ ]:
a=np.array(5)
print(a)

5


    2. 1 Dimension: Collection of 0 dimension arrays
        *   np.array([1,2,3])

In [ ]:
b=np.array([1,2,3])
print(b)

[1 2 3]


    3. 2 Dimension: Collection of 1 dimension arrays
        *   np.array([[1,2,3],[4,5,6]])

In [ ]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


    4. 3 Dimension: Collection of 2 dimension arrays
        *   np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Pandas

*   Used to make csv or json files to dataframes.
*   Used for working with a dataset for data cleaning and analysis.



In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('Titanic.csv')

Dataframes is a data structure with row and column in tabular form.

.loc[idx] function returns the row at 'idx' index.



In [ ]:
df.loc[0]

,0
Unnamed: 0,0
survived,0
pclass,3
sex,male
age,22.0
sibsp,1
parch,0
fare,7.25
embarked,S
class,Third


In [ ]:
df.loc[0:3] #Prints 0th, 1st, 2nd and 3rd row

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False


In [ ]:
print(df) #prints first 5 and last 5 rows

     Unnamed: 0  survived  pclass     sex   age  sibsp  parch     fare  \
0             0         0       3    male  22.0      1      0   7.2500   
1             1         1       1  female  38.0      1      0  71.2833   
2             2         1       3  female  26.0      0      0   7.9250   
3             3         1       1  female  35.0      1      0  53.1000   
4             4         0       3    male  35.0      0      0   8.0500   
..          ...       ...     ...     ...   ...    ...    ...      ...   
886         886         0       2    male  27.0      0      0  13.0000   
887         887         1       1  female  19.0      0      0  30.0000   
888         888         0       3  female   NaN      1      2  23.4500   
889         889         1       1    male  26.0      0      0  30.0000   
890         890         0       3    male  32.0      0      0   7.7500   

    embarked   class    who  adult_male deck  embark_town alive  alone  
0          S   Third    man        Tru

In [ ]:
print(df.to_string())

     Unnamed: 0  survived  pclass     sex    age  sibsp  parch      fare embarked   class    who  adult_male deck  embark_town alive  alone
0             0         0       3    male  22.00      1      0    7.2500        S   Third    man        True  NaN  Southampton    no  False
1             1         1       1  female  38.00      1      0   71.2833        C   First  woman       False    C    Cherbourg   yes  False
2             2         1       3  female  26.00      0      0    7.9250        S   Third  woman       False  NaN  Southampton   yes   True
3             3         1       1  female  35.00      1      0   53.1000        S   First  woman       False    C  Southampton   yes  False
4             4         0       3    male  35.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
5             5         0       3    male    NaN      0      0    8.4583        Q   Third    man        True  NaN   Queenstown    no   True
6             6     

In [ ]:
df.head() #prints first 5 rows

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [ ]:
df.head(6) #prints top 6 rows

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True


In [ ]:
df.tail() #prints bottom 5 rows

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True


In [ ]:
df.tail(6) #prints bottom 6 rows

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
885,885,0,3,female,39.0,0,5,29.125,Q,Third,woman,False,NaN,Queenstown,no,False
886,886,0,2,male,27.0,0,0,13.000,S,Second,man,True,NaN,Southampton,no,True
887,887,1,1,female,19.0,0,0,30.000,S,First,woman,False,B,Southampton,yes,True
888,888,0,3,female,NaN,1,2,23.450,S,Third,woman,False,NaN,Southampton,no,False
889,889,1,1,male,26.0,0,0,30.000,C,First,man,True,C,Cherbourg,yes,True
890,890,0,3,male,32.0,0,0,7.750,Q,Third,man,True,NaN,Queenstown,no,True
